name: mobile
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  vector_math: ^2.1.4
  persistent_bottom_nav_bar: ^5.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  adaptive_theme: ^3.4.1
  cached_network_image: ^3.3.0
  get_it: ^7.6.4
  sqflite: ^2.3.0
  dio: ^5.4.0
  internet_connection_checker: ^1.0.0+1
  either_dart: ^1.0.0
  shared_preferences: ^2.2.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/onBoarding/1.png
    - assets/images/onBoarding/1_1.png
    - assets/images/onBoarding/2.png
    - assets/images/onBoarding/2_2.png
    - assets/images/onBoarding/3.png
    - assets/images/onBoarding/3_3.png
    - assets/images/onBoarding/4.png
    - assets/images/onBoarding/4_4.png
    - assets/images/onBoarding/5.png
    - assets/images/onBoarding/5_5.png
  uses-material-design: true
